#
# Sera - OnePage Jekyll Template
# Configuration File
#
# Information for compile
exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "README.md"]
#
# If your website is placed in a separate folder on your server please modify
# this with your folder name, by default is empty.
# Example: Sera Demo is hosted on projects.gleesik.ro/sera-onepage
# If I compile Sera Template and I put in /sera-onepage without modifing baseurl
# than scripts can't be loaded corectly.
# For this example my site url is: projects.gleesik.ro (This can be just www.example.com)
# My folder for Demo Website is: /sera-onepage so baseurl: /sera-onepage
#
baseurl:

# the base hostname & protocol for your site
url: "https://adaptivebraces.com/"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Adaptive Braces
# Website language
lang: en-US
# Header Title
header-title: <strong>Adaptive Braces</strong>
# Header Tagline
headter-tagline: Next-generation Exoskeletons

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Download Now
  url: https://themeforest.net/collections/6069390-sera

# Secondary Buttons
header-secondary-button:
  title: Discover More
  url: http://themeforest.net/user/gleesik

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: kastner@mit.edu

# Offer Banner Link
# Default link is a link to all Sera OnePage products
# banner-link: https://themeforest.net/collections/6069390-sera

####################################
######  Global Social Links   ######
####################################
youtube: '#'
pinterest: '#'
facebook: '#'
twitter: '#'
google-plus: '#'
vimeo: '#'

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: head-shot.jpg
  author-name: David Kastner
  author-tagline: Bioengineer
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: '#'
    pinterest: '#'
    facebook: '#'
    twitter: '#'
    google-plus: '#'

# Google Map JS api
# This is my api for this template
key-api: AIzaSyDbnxVZQannH0GF4gtnnBFPiP9ofm2WqGs
map-text: Miss Bee
map-text-location: Vancouver, Canada
map-lat: 49.272155
map-lng: -123.104399

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Template created by Gleesik™
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Engineers and Designers
about-description: At Kahyton Biostructures, we are interested in developing innovative braces that can aid rehabilitation centers in providing patients with state of the art designs.
                     Our current research agenda focuses on using a unique organic structure such as the voronoi motif to strategically place openings over the inflicted area and facilitate therapy and the healing process.


#####################################
#############  Features  ############
features-title: Services
features-description: Kahyton Biostructures recently received recognition for its Adaptive Braces at the 2018 ASME 3D Printing Competition.
                   Special thanks to University of Brigham Young, ASME, and Dow Chemical for sponsoring the annual event.

#
# Features
#
features:

# Feature
- title: Personal Training
  description: Find your fit with Miss Bee. I offer highly customizeable programs tailored specifically for you.
  icon: pe-7s-user

# Feature
- title: Body Building
  description: Whatever your goals there's a plan to get you there.
  icon: pe-7s-gym

# Feature
- title: Injury Prevention
  description: Don't let persistent injuries keep you on the sidelines! Build a plan to get you back in play and stay off the sidelines.
  icon: pe-7s-bandaid


#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: A gallery style exhibition of the brace designs produced by Adaptive Braces.

#
# Portfolio Grid
#
portfolio-categories: [Black, White, Grey, 3D Render, Prototype]
portfolio:

# Portfolio Item 1
- title: M<span class="thin">iss</span> Bee
  categories: [Body Building, Personal Training]
  image: head-shot.jpg
  url: '#'

# Portfolio Item 2
- title: M<span class="thin">iss</span> Bee
  categories: [Body Building, Sport Training, Injury Prevention]
  image: FB1.jpg
  url: '#'

# Portfolio Item 3
- title: M<span class="thin">iss</span> Bee
  categories: [Personal Training, Sport Training, Injury Prevention]
  image: FB2.jpg
  url: '#'

# Portfolio Item 4
- title: M<span class="thin">iss</span> Bee
  categories: [Body Building]
  image: FB3.jpg
  url: '#'

# Portfolio Item 5
- title: M<span class="thin">iss</span> Bee
  categories: [Sport Training]
  image: FB4.jpg
  url: '#'

# Portfolio Item 6
- title: M<span class="thin">iss</span> Bee
  categories: [Injury Prevention]
  image: FB5.jpg
  url: '#'

#####################################
##########  Core Features  ##########
#####################################
core-title: Core Features
core-description: Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis aliquet diam ut eleifend.

#
# Core Features Left
#
core-features-left:

# Feature
- name: Creative
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-light

# Feature
- name: Minimalism
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-drop

# Feature
- name: Clean Coding
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-coffee

# Feature
- name: Friendly
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-smile

#
# Core Features Right
#
core-features-right:

# Feature
- name: Branding
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-wine

# Feature
- name: Web Design
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-monitor

# Feature
- name: Graphic Design
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-crop

# Feature
- name: Photography
  description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
  icon: pe-7s-camera


#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

#
# Testimonials
#
testimonials:

# Client
- name: Johnatan Doe
  url: http://themeforest.net
  url-text: ThemeForest.net
  avatar: avatar-01.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: themeforest.png

# Client
- name: Adam Smith
  url: http://codecanyon.net
  url-text: CodeCanyon.net
  avatar: avatar-02.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: codecanyon.png

# Client
- name: Irene Warner
  url: http://videohive.net
  url-text: VideoHive.net
  avatar: avatar-03.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: videohive.png

# Client
- name: Richard Ryan
  url: http://audiojungle.net
  url-text: AudioJungle.net
  avatar: avatar-04.jpg
  cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
  logo-img: audiojungle.png


#####################################
############# Our Blog ##############
#####################################
blog-title: Miss Bee's Blog
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.


#####################################
############### Team ################
#####################################
team-title: Meet Our Team
team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Team Members
#
team:

# Team Member
- name: Jack Skilton
  tagline: Graphic Designer
  avatar: avatar-01.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: James Young
  tagline: Developer
  avatar: avatar-02.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Johnatan Doe
  tagline: Hacker
  avatar: avatar-04.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'

# Team Member
- name: Ecaterina Doe
  tagline: Support Expert
  avatar: avatar-03.jpg

  # Social Links
  youtube: '#'
  pinterest: '#'
  facebook: '#'
  twitter: '#'
  google-plus: '#'
  vimeo: '#'


#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Pricing Tables
pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Plan Personal
#
plan-personal-price: $99
plan-personal-offer-1-title: 01 PSD Pack
plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: '#'

#
# Plan Business
#
plan-business-price: $499
plan-business-offer-1-title: 05 PSD Pack
plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: '#'

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: '#'


#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.


#####################################
#############   Footer   ############
#####################################
footer-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.
footer-copyright-text: MissBee&trade;
footer-copyright-url: http://findyourfitwithmissbee.com
footer-copyright-year: 2018
